begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,aud,role,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data)
select ('99000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'authenticated','authenticated','external'||n||'@test.invalid',now(),'{}','{}' from generate_series(1,4) n;
insert into public.profiles(id,display_name,role,status,crm_number,crm_state)
select ('99000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'Teste acordo '||n,'doctor','pending','99100'||n,'MA' from generate_series(1,4) n;
insert into private.registration_drafts(user_id,civil_name,cpf,birth_date,phone,data)
select ('99000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'Pessoa Teste '||n,'9900000000'||n,'1990-01-01','+559898888888'||n,'{"practicesMedicine":"yes"}' from generate_series(1,4) n;
create function pg_temp.actor(n integer) returns void language sql as $$ select set_config('request.jwt.claims',jsonb_build_object('sub','99000000-0000-4000-8000-'||lpad(n::text,12,'0'),'role','authenticated')::text,true)::text::void; $$;
create function pg_temp.payload(role_name text default 'owner') returns jsonb language sql as $$ select jsonb_build_object('creator_role',role_name,'recipient_email','external2@test.invalid','location','Hospital sintético','sector','UTI','starts_at',now()+interval '2 days','ends_at',now()+interval '3 days','value_cents',150000,'due_date',current_date+10,'payment_method','Pix','accepted',true); $$;
select ok(not has_table_privilege('authenticated','public.external_agreements','update'),'clients cannot rewrite agreements');
select ok(not has_table_privilege('anon','public.external_agreements','select'),'anonymous cannot read agreements');
select ok(not has_function_privilege('anon','public.external_agreement_command(uuid,text,uuid,jsonb)','execute'),'anonymous cannot execute commands');
select pg_temp.actor(1);
set local role authenticated;
select is(public.external_agreement_context()->>'eligible','true','complete pending account is eligible');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'create',null,pg_temp.payload()-'due_date')$$,'23502',null,'deadline required at database boundary');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'create',null,pg_temp.payload()||'{"accepted":false}')$$,'P0001','Confirme as condições','creator must accept');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'create',null,pg_temp.payload()||jsonb_build_object('starts_at',now()-interval '1 hour'))$$,'P0001','O plantão precisa estar no futuro','past shifts cannot be registered');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'create',null,pg_temp.payload()||'{"due_date":"infinity"}')$$,'23514',null,'infinite deadline cannot bypass mandatory due date');
select set_config('test.external_id',public.external_agreement_command('99000000-0000-4000-8000-000000000010','create',null,pg_temp.payload())::text,true);
select is(public.external_agreement_command('99000000-0000-4000-8000-000000000010','create',null,pg_temp.payload())::text,current_setting('test.external_id'),'create retry is idempotent');
select is((select count(*)::int from public.external_agreement_events where agreement_id=current_setting('test.external_id')::uuid),1,'retry does not duplicate event');
select throws_ok($$select public.external_agreement_command('99000000-0000-4000-8000-000000000010','create',null,pg_temp.payload()||'{"value_cents":200000}')$$,'P0001','Comando já utilizado com outros dados','same request cannot mutate content');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'accept',current_setting('test.external_id')::uuid,'{"accepted":true}')$$,'P0001','Convite indisponível para esta conta','creator cannot accept for recipient');
reset role;
select pg_temp.actor(3);
set local role authenticated;
select is((select count(*)::int from public.external_agreements where id=current_setting('test.external_id')::uuid),0,'forwarded invite reveals nothing to outsider');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'accept',current_setting('test.external_id')::uuid,'{"accepted":true}')$$,'P0001','Registro indisponível','outsider cannot accept');
reset role;
select pg_temp.actor(2);
set local role authenticated;
select is((select count(*)::int from public.external_agreements where id=current_setting('test.external_id')::uuid),1,'confirmed email recipient reads invitation');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'accept',current_setting('test.external_id')::uuid,'{"accepted":true,"terms_hash":"wrong"}')$$,'P0001','Revise e aceite as condições atuais','acceptance binds exact terms');
select lives_ok($$select public.external_agreement_command(gen_random_uuid(),'accept',current_setting('test.external_id')::uuid,jsonb_build_object('accepted',true,'terms_hash',(select terms_hash from public.external_agreements where id=current_setting('test.external_id')::uuid)))$$,'pending recipient accepts free agreement');
select is((select status from public.external_agreements where id=current_setting('test.external_id')::uuid),'confirmed','two accepts finalize without professional approval');
select ok((select document_hash=encode(extensions.digest(document_text,'sha256'),'hex') from public.external_agreements where id=current_setting('test.external_id')::uuid),'final canonical document hash verifies');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'payment',current_setting('test.external_id')::uuid,'{}')$$,'P0001','Pagamento indisponível','beneficiary cannot report as payer');
reset role;
select pg_temp.actor(1);
set local role authenticated;
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'receive',current_setting('test.external_id')::uuid,'{"accepted":true}')$$,'P0001','Confirmação de recebimento indisponível','payer cannot confirm receiving');
select lives_ok($$select public.external_agreement_command(gen_random_uuid(),'payment',current_setting('test.external_id')::uuid,jsonb_build_object('amount_cents',150000,'paid_on',current_date))$$,'payer records payment');
select ok((select received_at is null from public.external_agreements where id=current_setting('test.external_id')::uuid),'payment report is not receipt confirmation');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'payment',current_setting('test.external_id')::uuid,jsonb_build_object('amount_cents',150000,'paid_on','-infinity'))$$,'P0001','Data de pagamento inválida','non-finite payment dates are rejected at the database boundary');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'payment',current_setting('test.external_id')::uuid,jsonb_build_object('amount_cents',150000,'paid_on',current_date,'receipt_path','foreign/receipt.pdf'))$$,'P0001','Comprovante inválido','foreign receipt refused');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'payment',current_setting('test.external_id')::uuid,jsonb_build_object('amount_cents',50000,'paid_on',current_date))$$,'P0001','Informe o valor total do acordo','partial payment cannot be reported as full');
reset role;
select pg_temp.actor(2);
set local role authenticated;
select lives_ok($$select public.external_agreement_command(gen_random_uuid(),'dispute',current_setting('test.external_id')::uuid,'{"description":"Valor ainda não identificado na conta."}')$$,'beneficiary reports divergence');
select lives_ok($$select public.external_agreement_command(gen_random_uuid(),'receive',current_setting('test.external_id')::uuid,'{"accepted":true}')$$,'beneficiary confirms receipt');
select ok((select received_at is not null from public.external_agreements where id=current_setting('test.external_id')::uuid),'receipt is saved');
reset role;
select throws_ok($$update public.external_agreements set due_date=current_date+30 where id=current_setting('test.external_id')::uuid$$,'P0001','Condições imutáveis','even privileged accidental edits cannot change deadline');
select throws_ok($$delete from public.external_agreement_events where agreement_id=current_setting('test.external_id')::uuid$$,'P0001','Registro imutável','event history is append only');
select ok(not exists(select 1 from (select sequence,previous_hash,lag(event_hash) over(order by sequence) expected from public.external_agreement_events where agreement_id=current_setting('test.external_id')::uuid) e where previous_hash is distinct from expected),'event chain is continuous');
select ok(not exists(select 1 from public.external_agreement_events where agreement_id=current_setting('test.external_id')::uuid and event_hash<>encode(extensions.digest(canonical_text,'sha256'),'hex')),'event hashes verify');

-- Group approval remains independent, including initiator = substitute.
insert into public.institutions(id,name) values('99000000-0000-4000-8000-000000000100','Instituição sintética');
insert into public.groups(id,institution_id,name,requires_approval) values('99000000-0000-4000-8000-000000000101','99000000-0000-4000-8000-000000000100','Grupo sintético',true);
insert into public.group_memberships(group_id,profile_id,active,role) select '99000000-0000-4000-8000-000000000101',('99000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,true,case when n=3 then 'approver'::public.group_role else 'doctor'::public.group_role end from generate_series(1,3) n;
update public.profiles set status='approved',verification_valid_until=now()+interval '90 days' where id='99000000-0000-4000-8000-000000000003';
select pg_temp.actor(1);
set local role authenticated;
select set_config('test.group_id',public.external_agreement_command(gen_random_uuid(),'create',null,pg_temp.payload('substitute')||'{"group_id":"99000000-0000-4000-8000-000000000101"}')::text,true);
reset role;
select pg_temp.actor(2);
set local role authenticated;
select lives_ok($$select public.external_agreement_command(gen_random_uuid(),'accept',current_setting('test.group_id')::uuid,jsonb_build_object('accepted',true,'terms_hash',(select terms_hash from public.external_agreements where id=current_setting('test.group_id')::uuid)))$$,'recipient accepts group agreement');
select is((select status from public.external_agreements where id=current_setting('test.group_id')::uuid),'pending_approval','group requires institutional approval');
select is((select owner_id::text from public.external_agreements where id=current_setting('test.group_id')::uuid),'99000000-0000-4000-8000-000000000002','invited owner is payer when substitute initiates');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'approve',current_setting('test.group_id')::uuid)$$,'P0001','Aprovação institucional indisponível','party cannot approve without role');
reset role;
select pg_temp.actor(3);
set local role authenticated;
select lives_ok($$select public.external_agreement_command(gen_random_uuid(),'approve',current_setting('test.group_id')::uuid)$$,'active group approver finalizes');
select is((select status from public.external_agreements where id=current_setting('test.group_id')::uuid),'confirmed','institutional approval finalizes');
reset role;
update public.groups set active=false where id='99000000-0000-4000-8000-000000000101';
select pg_temp.actor(1);
set local role authenticated;
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'create',null,pg_temp.payload()||'{"group_id":"99000000-0000-4000-8000-000000000101"}')$$,'P0001','Vínculo de grupo necessário','inactive group cannot receive new agreements');
reset role;
select pg_temp.actor(4);
delete from private.registration_drafts where user_id='99000000-0000-4000-8000-000000000004';
set local role authenticated;
select is(public.external_agreement_context()->>'eligible','false','email-only account cannot accept without identification');
reset role;
update auth.users set email_confirmed_at=null where id='99000000-0000-4000-8000-000000000004';
set local role authenticated;
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'create',null,pg_temp.payload())$$,'P0001','Confirme seu e-mail','email confirmation is required');
reset role;
insert into public.external_agreements(id,creator_id,creator_role,recipient_email,owner_id,location,sector,starts_at,ends_at,value_cents,due_date,payment_method,terms,terms_hash)
values('99000000-0000-4000-8000-000000000200','99000000-0000-4000-8000-000000000001','owner','external2@test.invalid','99000000-0000-4000-8000-000000000001','Hospital sintético','UTI',now()-interval '1 minute',now()+interval '1 hour',150000,current_date+1,'Pix','{}','');
select pg_temp.actor(2);
set local role authenticated;
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'accept','99000000-0000-4000-8000-000000000200',jsonb_build_object('accepted',true,'terms_hash',(select terms_hash from public.external_agreements where id='99000000-0000-4000-8000-000000000200')))$$,'P0001','O prazo de confirmação terminou','expired invitation cannot be accepted');
reset role;
update public.profiles set status='suspended' where id='99000000-0000-4000-8000-000000000001';
select pg_temp.actor(1);
set local role authenticated;
select is(public.external_agreement_context()->>'eligible','false','suspended is not pending');
select throws_ok($$select public.external_agreement_command(gen_random_uuid(),'create',null,pg_temp.payload())$$,'P0001','Complete seu cadastro para registrar o acordo','suspended cannot initiate');
reset role;
select * from finish();
rollback;
